name: SonarQube Analysis

# Déclencheur d'événements pour l'exécution du pipeline
on:
  push:
    branches:
      - main  # Déclenche le workflow uniquement lors des pushes sur la branche 'main'
  pull_request:
    branches:
      - main  # Déclenche également pour les pull requests vers 'main'

jobs:
  sonar:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu

    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuration de Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Installation de SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-*/bin/sonar-scanner /usr/local/bin/

      # Analyse SonarQube
      - name: Run SonarQube Analysis
        run: |
          sonar-scanner -Dsonar.projectKey=RWB -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: sqp_7518c4ed7f073417c6ce7c1f77a90efcbc57ed54  # Utilisation du token stocké dans les secrets GitHub
